# Create a new ATM
# @name CreateAtm

POST {{HostAddress}}/atm
Content-Type: application/json

{ 
  "OpeningBalance": 15000.00
}

###

# Get ATM current balance

GET {{HostAddress}}/atm/{{CreateAtm.response.body.$.AtmId}}/balance

###

# Withdraw from ATM

POST {{HostAddress}}/atm/{{CreateAtm.response.body.$.AtmId}}/withdraw
Content-Type: application/json

{ 
  "AccountId": "{{CreateAccount.response.body.$.AccountId}}",
  "Amount": 50.00
}

###

# Create Account
# @name CreateAccount

POST {{HostAddress}}/account
Content-Type: application/json

{ 
  "OpeningBalance": 5000.00
}

###

# Retrieves Account current balance

GET {{HostAddress}}/account/{{CreateAccount.response.body.$.AccountId}}/balance

###

# Creates a debit in an account

POST {{HostAddress}}/account/{{CreateAccount.response.body.$.AccountId}}/debit
Content-Type: application/json

{ 
  "Amount": 15.00
}

###

# Creates a credit into an account

POST {{HostAddress}}/account/{{CreateAccount.response.body.$.AccountId}}/credit
Content-Type: application/json

{ 
  "Amount": 30.00
}

###

# Creates a recurring payment on an Account

POST {{HostAddress}}/account/{{CreateAccount.response.body.$.AccountId}}/recurring_payment
Content-Type: application/json

{ 
  "Amount": 10.00,
  "PeriodInMinutes": 1
}

###

# Get customer net worth
# For this example's sake, the customer ID will be the same as account ID

GET {{HostAddress}}/customer/{{CreateAccount.response.body.$.AccountId}}/net_worth

###

# Add account to customer.

POST {{HostAddress}}/customer/{{CreateAccount.response.body.$.AccountId}}/add_account
Content-Type: application/json

{
  "AccountId": "{{CreateAccount.response.body.$.AccountId}}"
}

###

# Executes transfer between accounts (stateless grain example)

POST {{HostAddress}}/transfer
Content-Type: application/json

{
  "FromAccountId": "1cb83fb9-1cd9-4df7-9dc1-b48612a176d5",
  "ToAccountId": "9f5f8f02-c1dd-45b8-8859-0fca672bddaa",
  "Amount": 123.00
}

###